[general]
threads = 50
timeout = 10
queue = "file"

seeds = ["https://soyjak.party", "https://4chan.org"]

[target.apache]
version = "2.4.52-57"
log = "apache.log"
execute = "./exploit.sh"
misconfig = true

[target.nginx]
version = "1.27.2"
log = "nginx.log"
misconfig = false


